### PR TITLE
[flutter_appauth][flutter_appauth_platform_interface] add responseMode as parameter for android and ios

### PR DESCRIPTION
**Pull request by sbarth**
As this repository hosts two packages, please ensure the PR title starts with the name of the package that it relates to using square brackets (e.g. [flutter_appauth])

### CODE REVIEW

**Comment by MaikuB** [comment]
Thanks for the PR. Looks like the build is failing as one of the tests needs to be updated to match the changes as well. Would you be able to update that?

**Comment by sbarth** [comment]
Ok, fixed it finally. It was my first dart test and I didn't understand the problem ;-)
Can you take a look into flutter_appauth/pubspec.yaml, I don't know what I have to set there. Maybe I have to split this PR into 2 separate and create first PR for flutter_appauth/flutter_appauth_platform_interface and then for flutter_appauth/flutter_appauth and use the version number?

**Comment by MaikuB** [comment]
Thanks. It's not necessary to split them. The reason it's not necessary is that `flutter_appauth`'s dependency on `flutter_appauth_platform_interface` is defined such that it can pull down versions newer than 3.0.0 inclusive but older than 4.0.0. This means when 3.1.0 is published, it's possible for those on that even on  version 1.0.0 of `flutter_appauth` to pull the changes that were made to the platform interface such that it's not necessary to publish a new version. However, it's better to do so to notify others of the changes done as the platform interface is a transitive dependency of the plugin.

I haven't gotten around to testing it yet but changes look straightforward so I don't anticipate there being any issues. The remaining changes I see needed for the PR are

- revert the changes done to `flutter_app_appauth`'s pubspec.yaml on how the dependency on the platform interface is defined
- to bump the version of `flutter_appauth_platform_interface` to 3.1.0 and add a changelog entry.
- to bump `flutter_app_appauth` to 1.1.0 with a changelog entry on it too

Are the last two something you're ok with pushing to this PR? Otherwise I could also do this provided you had enabled the setting that allows edits from maintainers.

**Comment by sbarth** [comment]
- [x] revert the changes done to flutter_app_appauth's pubspec.yaml on how the dependency on the platform interface is defined 
- [x] to bump the version of flutter_appauth_platform_interface to 3.1.0 and add a changelog entry.
- [x] to bump flutter_app_appauth to 1.1.0 with a changelog entry on it too 

All ok for me :-)

**Comment by MaikuB** [comment]
Thanks. I've amended the changelog a bit and added `responseMode` as a parameter to `AuthorizationRequest` as well

**Pull request merged**
