### PR TITLE
[flutter_appauth][flutter_appauth_platform_interface] Add State as an optional field to AuthorizationTokenRequest and Authorization Request

### PR DESCRIPTION
**Pull request by NateS2**
Adds State as an optional field to authorization and authorization token requests. The reason being is Android App-Auth includes a builder for the state parameter and will throw an error when trying to place state in additional parameters

### CODE REVIEW

**Comment by NateS2** [comment]
#94

**Comment by MaikuB** [comment]
Thanks for the PR. I'll see if I can take a look at it later in the week

**Comment by mehdok** [comment]
Beside `state`, same situation applies for `response_type`, `code_challenge_method` and `code_challenge`

**Comment by MaikuB** [comment]
@mehdok note that this is a PR not an issue that you're responding to. Submit a PR if you need changes for your situation

**Comment by MaikuB** [comment]
@NateS2 wanted to touch base to see if you plan to on fixing the iOS issue. Otherwise I may have to close this unless someone else wants to pick up from where the PR has left off

**Comment by MaikuB** [comment]
Unfortunately have to close this due to lack of further updates

**Comment by A-a-l-l-e-e-x-x** [comment]
Isn't this required functionality to be able to use AppAuth, though? Most "bigger" 3rd party services I'm aware of require some of the mentioned parameters, how do we use the library if we cannot pass those parameters?

**Comment by Nirajn2311** [comment]
> This is failing on iOS and likely needs changing to address

Hi, what's failing on iOS. I'll work on this as I need this parameter for my use case.

**Comment by MaikuB** [comment]
I can't recall the specifics as it's been a long time. Perhaps the issue did get fixed and I missed it but if you're going to work on this then you can go ahead and submit a new PR

**Comment by Nirajn2311** [comment]
My colleague has opened a PR for it - https://github.com/MaikuB/flutter_appauth/pull/321

**Pull request closed without merging**
